#!/bin/bash
_opt=$1
CONDA_ENV_NAME=01
PROJECT_DIR=/Users/tesla/Projects/01/software

function found_exe() {
	hash "$1" 2>/dev/null
}

# If tput is available and can handle multiple colors
if found_exe tput; then
	if [[ $(tput colors) != "-1" && -z $CI ]]; then
		GREEN=$(tput setaf 2)
		BLUE=$(tput setaf 4)
		CYAN=$(tput setaf 6)
		YELLOW=$(tput setaf 3)
		RED=$(tput setaf 1)
		RESET=$(tput sgr0)
		HIGHLIGHT=$YELLOW
	fi
fi

eval "$(conda shell.bash hook)"
conda activate $CONDA_ENV_NAME

# Initialize default values
mode="default"

# Parse command line options
while [[ "$#" -gt 0 ]]; do
    case "$1" in
        -d|--dev)
            mode="dev"
            shift
            ;;
        *)
            echo "Invalid option: $1" >&2
            exit 1
            ;;
    esac
done

if [ "$mode" = "dev" ]; then
	echo "$CYAN running in dev mode... $RESET"
	cd $PROJECT_DIR || exit
	# find . -type f -name "*.py" | entr -cr python server.py
	find . -type f -name "*.py" | entr -cr poetry run 01
else
	cd $PROJECT_DIR || exit
	# 	python server.py
	poetry run 01
fi
